name: Deploy Bundle & Run Databricks Job

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy Databricks Asset Bundle
        run: databricks bundle deploy -t ${{ secrets.DEPLOY_TARGET}}
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Deploy Streamlit App
        run: databricks apps deploy kingfisher-streamlit-app
          --source-code-path /Workspace/Users/${{ secrets.DATABRICKS_USER }}/.bundle/kingfisher-wells-streamlit/${{ env.DEPLOY_TARGET }}/files/src/app
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Get job ID for kingfisher_wells_full_medallion
        id: jobid
        run: |
          job_id=$(databricks jobs list --output json | jq -r '.[] | select(.settings.name=="kingfisher_wells_full_medallion") | .job_id')
          echo "job_id=$job_id" >> $GITHUB_OUTPUT
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Run Databricks Job (kingfisher_wells_full_medallion)
        run: databricks jobs run-now ${{ steps.jobid.outputs.job_id }}
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
